# Generated by Django 5.0.6 on 2024-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_home_title_alter_bodies_title_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
